### ISSUE TITLE
test_full.py working but results in exception

### ISSUE THREAD

**Issue by jrubin01** [yaq007/Autofocus-Layer#1]
Running python test_full.py works, but gives the following exception as score and pred_seg are not defined in the test() method:

Traceback (most recent call last):
  File "test_full.py", line 228, in <module>
    main(args)
  File "test_full.py", line 139, in main
    test(test_loader, model, args)      
  File "test_full.py", line 112, in test
    return score, pred_seg
NameError: name 'score' is not defined

**Comment by yaq007** [comment]
Hi Jonathan,

Thanks for your contact about the bug. Please just remove the line 112 in
test "return score, pred_seg". It should work now. If not, please let me
know and I will check the problem further.

Best,
Yao
