### ISSUE TITLE
DATa loader

### ISSUE THREAD

**Issue by DamperHa** [yaq007/Autofocus-Layer#9]

**Comment by DamperHa** [comment]
Thank you for your sharing,
The following error occurred when I ran the code,
`
Traceback (most recent call last):
  File "test/test_dataset.py", line 16, in test_dataset
    for i, j in enumerate(dataload):
  File "/home/ubuntu/fzh/.conda/envs/rando/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/ubuntu/fzh/.conda/envs/rando/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "/home/ubuntu/fzh/.conda/envs/rando/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/ubuntu/fzh/.conda/envs/rando/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/ubuntu/fzh/RF/RF_code/dataset/train_data.py", line 52, in __getitem__
    sample = transform(sample.copy())
  File "/home/ubuntu/fzh/RF/RF_code/dataset/train_data.py", line 78, in __call__
    choose = random.sample(range(0, len(index)), 1)
  File "/home/ubuntu/fzh/.conda/envs/rando/lib/python3.6/random.py", line 320, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative


`
Thank for your help.
